version: '3.8'

# Docker Images are notorious for having endless security vulnerabilities,
# but no one speaks about this for some reason. Rapidfort hardens their
# most common images and releases it to the public with a self-reported
# massive-albeit incomplete overhaul of the code. I need to inspect these
# images manually before entering sensitive data, but this seems to be
# suitable for testing purposes.

services:
  db:
    image: rapidfort/postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"